apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: https-test
spec:
  tls:
  - hosts:
    - www.huangming.org
    secretName: huangming.org
  rules:
  - host: www.huangming.org
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
